# Generated by Django 5.1.3 on 2024-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
